### ISSUE TITLE
Version 0.6.X does not support importing wallet from file, which is created in previous versions

### ISSUE THREAD

**Issue by zhenkas** [BitShares/bitshares#1406] opened 2015-02-26 11:22 UTC
Reproduced with Bitshares Client for Windows
1. Export wallet from version 0.5.3 (my wallet contained about 20 accounts + 1 delegate account)
2. Import wallet on version 0.6.0/1
3. Error

Workaround I did apply:
1. Upgrade 0.5.3 to version 0.6.X
2. Re-export the wallet
3. Import works

**Comment by vikramrajkumar** [comment] 2015-02-26 17:45
@zhenkas Are you getting the same "invalid password" error as described in this thread: https://bitsharestalk.org/index.php?topic=14330.msg186561#msg186561 ?

If possible, can you try importing with 0.6.2 and let me know if you still have the same problem ?

**Comment by zhenkas** [comment] 2015-02-27 16:45
The error reproduced on 0.6.2.
I attached the error screen shots.
Note, that the errors are different between 0.6.0 and 0.6.1+ versions

0.6.0:
![error 0 6 0](https://cloud.githubusercontent.com/assets/858377/6416696/a7380228-beb0-11e4-8b2c-b235f5ece907.png)
0.6.1,0.6.2
![error 0 6 1-0 6 2](https://cloud.githubusercontent.com/assets/858377/6416697/a7cc5f9a-beb0-11e4-80b8-73b0224606ad.png)

**Comment by vikramrajkumar** [comment] 2015-03-30 23:00
Still have no clue as to the cause here. I've read the version diffs for bitshares, qt_wallet, and fc many times and see nothing; also unable to reproduce. Unfortunately I will close this for now and using 0.5.3 will be the official workaround for old backups with this problem.

**Closed by vikramrajkumar** 2015-03-30 23:00 UTC
Labels: vikram
