### ISSUE TITLE
Using cmake with with boost .so libs is currently impossible because Boost_USE_STATIC_LIBS is hardcoded to ON

### ISSUE THREAD

**Issue by wildbunny** [BitShares/bitshares#1056] opened 2014-11-25 10:41 UTC
Seems that Boost_USE_STATIC_LIBS is hardcoded to ON inside https://github.com/BitShares/fc/blob/master/CMakeModules/FindBoost.cmake, which means it overrides the command line switch to disable that. This causes cmake to fail when you only have .so files for boost.

**Comment by pmconrad** [comment] 2015-04-10 12:24
FTR: I've always built my linux packages with Boost_USE_STATIC_LIBS OFF . I didn't need to link with atomic, though.

The only issue I've had is that when compile the boost-based unit tests the flag BOOST_TEST_DYN_LINK must be defined. Any idea how to detect static/dynamic linking at compile time, or maybe in CMakeLists.txt?

**Comment by wildbunny** [comment] 2015-04-10 12:41
My problem with this is that it is still hardcoded to on inside
https://github.com/BitShares/fc/blob/master/CMakeModules/FindBoost.cmake

On 10 April 2015 at 13:24, Peter Conrad <notifications@github.com> wrote:

> FTR: I've always built my linux packages with Boost_USE_STATIC_LIBS OFF .
> I didn't need to link with atomic, though.
>
> The only issue I've had is that when compile the boost-based unit tests
> the flag BOOST_TEST_DYN_LINK must be defined. Any idea how to detect
> static/dynamic linking at compile time, or maybe in CMakeLists.txt?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BitShares/bitshares/issues/1056#issuecomment-91536140>
> .
>



-- 
Paul Firth
http://www.wildbunny.co.uk/blog
http://twitter.com/paul_m_firth

**Comment by shawnpringle** [comment] 2015-04-13 20:37
On 04/10/2015 09:24 AM, Peter Conrad wrote:
> FTR: I've always built my linux packages with Boost_USE_STATIC_LIBS OFF . I didn't need to link with atomic, though.
>
> The only issue I've had is that when compile the boost-based unit tests the flag BOOST_TEST_DYN_LINK must be defined. Any idea how to detect static/dynamic linking at compile time, or maybe in CMakeLists.txt?
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/BitShares/bitshares/issues/1056#issuecomment-91536140
>
Have you tried getting rid of all of the hard coded settings altogether? 
  Maybe the build system would do the right thing(tm) and just use 
static iff it cannot do things dynamically.

Shawn Pringle

**Comment by pmconrad** [comment] 2015-04-14 20:44
Found a workaround, assuming that static libraries end with ".a" on all supported platforms. Tested on linux (openSUSE for dynamic, ubuntu for static). Can someone check this on windows and if possible mac?

https://github.com/BitShares/fc/compare/master...pmconrad:dynamic_boost
https://github.com/BitShares/bitshares/compare/develop...pmconrad:dynamic_boost

**Comment by dnotestein** [comment] 2015-04-14 21:08
Static libs don't end with .a on windows, they end in .lib (also note that import libraries also end in .lib, so just because a file ends in .lib doesn't mean it's a static lib).

**Comment by pmconrad** [comment] 2015-04-15 16:47
> Static libs don't end with .a on windows, they end in .lib

After some googling it seems that there is no "best" solution for this. Most projects seem to just ignore the problem and assume dynamic linking. Another option is to use a "headers-only" version of the unit test framework, at the expense of higher compile times for the test programs.

I have found one project that sets BOOST_TEST_DYN_LINK depending on the setting of Boost_USE_STATIC_LIBS, but AFAICT on windows dynamic libraries will be used when no static libs can be found, so this isn't reliable.

The good thing is that FindBoost.cmake only checks for .lib and .a (and for $CMAKE_FIND_LIBRARY_SUFFIXES on windows) when static linking is selected, so if I integrate .lib into my check it *should* reliably detect the actual library type being used.

Opinions?

**Comment by shawnpringle** [comment] 2015-04-16 17:15
On 04/15/2015 01:47 PM, Peter Conrad wrote:
>> Static libs don't end with .a on windows, they end in .lib
>
> After some googling it seems that there is no "best" solution for this. Most projects seem to just ignore the problem and assume dynamic linking. Another option is to use a "headers-only" version of the unit test framework, at the expense of higher compile times for the test programs.
>
> I have found one project that sets BOOST_TEST_DYN_LINK depending on the setting of Boost_USE_STATIC_LIBS, but AFAICT on windows dynamic libraries will be used when no static libs can be found, so this isn't reliable.
>
> The good thing is that FindBoost.cmake only checks for .lib and .a (and for $CMAKE_FIND_LIBRARY_SUFFIXES on windows) when static linking is selected, so if I integrate .lib into my check it *should* reliably detect the actual library type being used.
>
> Opinions?
>

For each library of boost that is required //x//, check to see if 
lib//x//.so exists.  If they all exist, you can link it dynamically and, 
failing that, use static.  When upgrades fix things you need to 
recompile every static package, and that's bad.

Shawn

**Comment by pmconrad** [comment] 2015-04-16 19:20
> For each library of boost that is required //x//, check to see if
lib//x//.so exists.  If they all exist, you can link it dynamically and,
failing that, use static.  When upgrades fix things you need to
recompile every static package, and that's bad.

I think this is what FindBoost.cmake is supposed to do, and what it does a good job of AFAICT.

The only problem caused by this is related to the unit test framework, which behaves differently at compile time depending on whether it's linked against the static or the dynamic version of libboost_unit_test_framework (and only this). This problem can be worked around by checking if that specific library ends in .a or .lib, IMO.

Or did I miss something?

**Comment by vikramrajkumar** [comment] 2015-04-28 14:53
Assuming this is fixed by @pmconrad's patches:
- https://github.com/BitShares/fc/pull/5
- https://github.com/BitShares/bitshares/pull/1521

**Closed by vikramrajkumar** 2015-04-28 14:53 UTC
