### ISSUE TITLE
short selling - changed the display of the APR

### ISSUE THREAD

**Issue by grzegorzs** [BitShares/bitshares#1296] opened 2015-01-22 14:45 UTC
Regression tests `wallet_market_submit_short` and `wallet_market_cancel_order`
Are you sure MEMO column is displayed correctly?
Parameter `interest_rate (string, required): the APR you wish to pay interest at (0.0% to 1000.0%))`
`interest_rate = 50`
`MEMO = short XMO @ 0.05% APR`
previously
`MEMO = short XMO @ 50.% APR`

```
default (unlocked) >>> wallet_market_submit_short test 100 XTS 50 XMO 3.3334
TIMESTAMP           BLOCK     FROM                TO                  AMOUNT                  MEMO                                        FEE                 ID      
======================================================================================================================================================================
2014-06-20T14:40:50 PENDING   test                test                100.00000 XTS           short XMO @ 0.05% APR                       0.50000 XTS         36193374

```

**Comment by bytemaster** [comment] 2015-01-22 17:57
Looks like the memo is wrong now.

**Comment by theoreticalbts** [comment] 2015-01-22 18:37
@bytemaster believes my changes to https://github.com/BitShares/bitshares/blob/32dc72dd6234f3c4580222cfa211d8b082de4576/libraries/wallet/wallet.cpp#L446-452 introduced in 32dc72dd6234f3c4580222cfa211d8b082de4576 are the cause.  (I never wanted this commit to be merged, but @bytemaster has issues with my git workflow and is urging me to commit more frequently, even code that is untested or broken.  This commit certainly falls into that category -- as evidenced by the commit message, I never intended it to be merged.)

We knew it was working in the past.  We know it doesn't work in the present.  At some point, a critical commit must have been introduced that changed the behavior.  There is some doubt about which commit caused the breakage.  We can easily write a shell script to tell whether a given commit is good or bad.

This looks like a job for `git bisect`.  Here's how I did it:

    git checkout 205b341a9bb02066bfdd54dc2a0c5736847f5041
    git bisect bad
    git checkout 4085e808523d1eed12166d0dfb571706d4370b88
    git bisect good
    cat >issue_1296_bisect.sh <<EOF
    #!/bin/sh

    set -x

    make -j8 wallet_tests || exit 1
    sh -c 'cd tests && ./wallet_tests -t regression_tests_without_network/wallet_market_submit_short | grep "50[.]%"' || exit 1
    EOF
    chmod 755 issue_1296_bisect.sh
    git bisect run

The `bisect` command will recompile multiple times, testing whether each version suffers from the issue, and selecting the next commit to test in such a way as to halve the region where the critical commit might be (which is non trivial if there are merges).

**Comment by theoreticalbts** [comment] 2015-01-22 18:46
Heh, before the bisect even finished I realized what the issue is.  The `apply_order_to_builder` caller is now responsible for specifying `needs_satoshi_conversion` which specifies whether `order_price` must be converted to satoshis or not.  When changing the API in this way, of course all existing call sites must specify the flag.  I thought it would be `true` for existing order types, but actually for short orders is `false` because `price_arg` is an APY percentage for short orders.

The price is now overloaded to have three different semantics:  A percentage of the feed for relative orders, an APY for short orders, or an actual price for absolute bids/asks.

**Closed** 2015-01-22 19:27 UTC
