### ISSUE TITLE
[BitShares 0.5.0] Issue building multest.cpp on Ubuntu 14.04 i686

### ISSUE THREAD

**Issue by robrigo** [BitShares/bitshares#1256] opened 2015-01-15 17:19 UTC
This happens when I run a full "make". What target should I make against if I want to only compile mission critical code for a headless delegate?

```
[100%] Building CXX object tests/drltc_tests/fc_math/CMakeFiles/multest.dir/multest.cpp.o
/home/user/bitshares/tests/drltc_tests/fc_math/multest.cpp: In function ‘int main(int, char**, char**)’:
/home/user/bitshares/tests/drltc_tests/fc_math/multest.cpp:136:27: error: conversion from ‘__time_t {aka long int}’ to ‘fc::uint128’ is ambiguous
                 ns_before = t_before.tv_sec;
                           ^
/home/user/bitshares/tests/drltc_tests/fc_math/multest.cpp:136:27: note: candidates are:
In file included from /home/user/bitshares/tests/drltc_tests/fc_math/multest.cpp:4:0:
/home/user/bitshares/libraries/fc/include/fc/uint128.hpp:27:7: note: fc::uint128::uint128(uint64_t)
       uint128( uint64_t l ):hi(0),lo(l){}
       ^
/home/user/bitshares/libraries/fc/include/fc/uint128.hpp:26:7: note: fc::uint128::uint128(int64_t)
       uint128( int64_t l ):hi( -(l<0) ),lo(l){}
       ^
/home/user/bitshares/libraries/fc/include/fc/uint128.hpp:25:7: note: fc::uint128::uint128(int32_t)
       uint128( int32_t l ):hi( -(l<0) ),lo(l){}
       ^
/home/user/bitshares/libraries/fc/include/fc/uint128.hpp:24:7: note: fc::uint128::uint128(uint32_t)
       uint128( uint32_t l ):hi(0),lo(l){}
       ^
/home/user/bitshares/libraries/fc/include/fc/uint128.hpp:18:9: error:   initializing argument 1 of ‘fc::uint128& fc::uint128::operator=(fc::uint128&&)’
   class uint128
         ^
/home/user/bitshares/tests/drltc_tests/fc_math/multest.cpp:138:27: error: conversion from ‘__syscall_slong_t {aka long int}’ to ‘const fc::uint128’ is ambiguous
                 ns_before += t_before.tv_nsec;
                           ^
/home/user/bitshares/tests/drltc_tests/fc_math/multest.cpp:138:27: note: candidates are:
In file included from /home/user/bitshares/tests/drltc_tests/fc_math/multest.cpp:4:0:
/home/user/bitshares/libraries/fc/include/fc/uint128.hpp:27:7: note: fc::uint128::uint128(uint64_t)
       uint128( uint64_t l ):hi(0),lo(l){}
       ^
/home/user/bitshares/libraries/fc/include/fc/uint128.hpp:26:7: note: fc::uint128::uint128(int64_t)
       uint128( int64_t l ):hi( -(l<0) ),lo(l){}
       ^
/home/user/bitshares/libraries/fc/include/fc/uint128.hpp:25:7: note: fc::uint128::uint128(int32_t)
       uint128( int32_t l ):hi( -(l<0) ),lo(l){}
       ^
/home/user/bitshares/libraries/fc/include/fc/uint128.hpp:24:7: note: fc::uint128::uint128(uint32_t)
       uint128( uint32_t l ):hi(0),lo(l){}
       ^
/home/user/bitshares/libraries/fc/include/fc/uint128.hpp:54:16: error:   initializing argument 1 of ‘fc::uint128& fc::uint128::operator+=(const fc::uint128&)’
       uint128& operator += ( const uint128& u ) { const uint64_t old = lo; lo += u.lo;  hi += u.hi + (lo < old); return *this; }
                ^
/home/user/bitshares/tests/drltc_tests/fc_math/multest.cpp:140:26: error: conversion from ‘__time_t {aka long int}’ to ‘fc::uint128’ is ambiguous
                 ns_after = t_after.tv_sec;
                          ^
/home/user/bitshares/tests/drltc_tests/fc_math/multest.cpp:140:26: note: candidates are:
In file included from /home/user/bitshares/tests/drltc_tests/fc_math/multest.cpp:4:0:
/home/user/bitshares/libraries/fc/include/fc/uint128.hpp:27:7: note: fc::uint128::uint128(uint64_t)
       uint128( uint64_t l ):hi(0),lo(l){}
       ^
/home/user/bitshares/libraries/fc/include/fc/uint128.hpp:26:7: note: fc::uint128::uint128(int64_t)
       uint128( int64_t l ):hi( -(l<0) ),lo(l){}
       ^
/home/user/bitshares/libraries/fc/include/fc/uint128.hpp:25:7: note: fc::uint128::uint128(int32_t)
       uint128( int32_t l ):hi( -(l<0) ),lo(l){}
       ^
/home/user/bitshares/libraries/fc/include/fc/uint128.hpp:24:7: note: fc::uint128::uint128(uint32_t)
       uint128( uint32_t l ):hi(0),lo(l){}
       ^
/home/user/bitshares/libraries/fc/include/fc/uint128.hpp:18:9: error:   initializing argument 1 of ‘fc::uint128& fc::uint128::operator=(fc::uint128&&)’
   class uint128
         ^
/home/user/bitshares/tests/drltc_tests/fc_math/multest.cpp:142:26: error: conversion from ‘__syscall_slong_t {aka long int}’ to ‘const fc::uint128’ is ambiguous
                 ns_after += t_after.tv_nsec;
                          ^
/home/user/bitshares/tests/drltc_tests/fc_math/multest.cpp:142:26: note: candidates are:
In file included from /home/user/bitshares/tests/drltc_tests/fc_math/multest.cpp:4:0:
/home/user/bitshares/libraries/fc/include/fc/uint128.hpp:27:7: note: fc::uint128::uint128(uint64_t)
       uint128( uint64_t l ):hi(0),lo(l){}
       ^
/home/user/bitshares/libraries/fc/include/fc/uint128.hpp:26:7: note: fc::uint128::uint128(int64_t)
       uint128( int64_t l ):hi( -(l<0) ),lo(l){}
       ^
/home/user/bitshares/libraries/fc/include/fc/uint128.hpp:25:7: note: fc::uint128::uint128(int32_t)
       uint128( int32_t l ):hi( -(l<0) ),lo(l){}
       ^
/home/user/bitshares/libraries/fc/include/fc/uint128.hpp:24:7: note: fc::uint128::uint128(uint32_t)
       uint128( uint32_t l ):hi(0),lo(l){}
       ^
/home/user/bitshares/libraries/fc/include/fc/uint128.hpp:54:16: error:   initializing argument 1 of ‘fc::uint128& fc::uint128::operator+=(const fc::uint128&)’
       uint128& operator += ( const uint128& u ) { const uint64_t old = lo; lo += u.lo;  hi += u.hi + (lo < old); return *this; }
                ^
make[2]: *** [tests/drltc_tests/fc_math/CMakeFiles/multest.dir/multest.cpp.o] Error 1
make[1]: *** [tests/drltc_tests/fc_math/CMakeFiles/multest.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by dnotestein** [comment] 2015-01-15 17:22
Eric and I were just discussing yesterday that a lot of these misc test targets that aren't actively run should be removed from the default build process.

**Comment by theoreticalbts** [comment] 2015-01-15 18:13
Duplicate of #1228, fixed by 2602504998dcd63788e106260895769697f62b07 .  @vikramrajkumar : if there will be an 0.5.1, this patch should go into it, just to keep people who run `make` without specifying a target from running into this issue.  As @dnotestein rightly points out, our build system shouldn't build test code in the default target.

Although we want to take "build-the-world" out of the default target, we should put it into an `all` target which will continue to building everything that can be built on the user's system.  This will be helpful because people using compiler versions, compilers or OS's that we do not, can run `make all` and report build breakage.

@robrigo : `make bitshares_client` is adequate if you do not need the GUI wallet.  What compiler version are you using?  For `gcc` this is reported by `g++ --version`

It seems strange that this problem surfaces on 14.04 since I run 14.04 and I am in the habit of never pushing patches until they at least compile for me...

**Comment by robrigo** [comment] 2015-01-15 18:22
Thanks, make bitshares_client worked. Using gcc 4.8.2.

**Comment by vikramrajkumar** [comment] 2015-01-15 20:37
@emfrias Can you remove the tests from the default build target but leave them in an `all` target as described by @theoreticalbts above?

**Comment by vikramrajkumar** [comment] 2015-01-16 19:05
Build target issue moved to: #1265
Closing this as duplicate of: #1228

**Closed by vikramrajkumar** 2015-01-16 19:05 UTC
