### ISSUE TITLE
a serious bug

### ISSUE THREAD

**Issue by RoyBts** [BitShares/bitshares#1526] opened 2015-04-30 15:26 UTC
some people include me have  a problem that there is`t any reaction after input unlocking secret   after update to 0.9

**Comment by abitmore** [comment] 2015-04-30 19:51
"Wallet database will be upgraded on first login; this can take a long time", which could be an hour. Is your issue like this?

**Comment by vikramrajkumar** [comment] 2015-05-01 15:45
> "Wallet database will be upgraded on first login; this can take a long time"

This is probably the cause, and should be somewhat addressed by @abitmore's patch: #1525

Otherwise, this is probably duplicate of: https://github.com/BitShares/web_wallet/issues/641

**Closed by vikramrajkumar** 2015-05-01 15:45 UTC
